- type: job
  id: SecurityCadet
  name: job-name-cadet
  description: job-description-cadet
  playTimeTracker: JobSecurityCadetOld
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 36000 #10 hrs # Corvax-RoleTime
    - !type:DepartmentTimeRequirement
      department: Security
      time: 72000 #20 hrs # Corvax-RoleTime
      inverted: true # stop playing intern if you're good at security!
  startingGear: SecurityCadetGear
  icon: "JobIconSecurityCadet"
  supervisors: job-supervisors-security
  canBeAntag: false
  ## Frontier: commented out stuff below
  # access:
  # - Security
  # - Brig
  # - Maintenance
  # - Service
  # - External
  # - Cryogenics
  # special:
  # - !type:AddImplantSpecial
  #   implants: [ MindShieldImplant ]
  ## End Frontier: commented out stuff above
  setPreference: false # Frontier
  accessGroups: # Frontier
  - GeneralAccess # Frontier

- type: startingGear
  id: SecurityCadetGear
  equipment:
<<<<<<< HEAD
    shoes: ClothingShoesBootsJackFilled
=======
    shoes: ClothingShoesBootsJackSec # Corvax-Resprite-MRP
>>>>>>> r1remote/master
    outerClothing: ClothingOuterArmorBasic
    id: SecurityCadetPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolMk58
    pocket2: HyperLinkBookCorporateLaw # Corvax-HyperLink
  storage:
    back:
    - Flash
    - MagazinePistol
