contact_links:
  - name: Предложение
    url: https://discord.gg/x2zEg7kWNr
    about: Свои предложения можете оставлять в соответствующем канале Discord.
  - name: Сообщить об уязвимости
    url: https://discord.gg/x2zEg7kWNr
    about: Пожалуйста, сообщайте о серьезных эксплойтах и уязвимостях безопасности Dan#2265 / KIBORG#2774 / Dushess#7066 в Discord.
