- type: job
  id: StationEngineer
  name: job-name-engineer
  description: job-description-engineer
  playTimeTracker: JobStationEngineer
  setPreference: false # Frontier
  requirements:
<<<<<<< HEAD
    - !type:OverallPlaytimeRequirement
      time: 10800
=======
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 18000 #5 hrs # Corvax-RoleTime
>>>>>>> r1remote/master
  startingGear: StationEngineerGear
  icon: "JobIconStationEngineer"
  supervisors: job-supervisors-hire # Frontier
  accessGroups: # Frontier
  - GeneralAccess # Frontier

- type: startingGear
  id: StationEngineerGear
  equipment:
    eyes: ClothingEyesGlassesMeson
#    belt: ClothingBeltUtilityEngineering # Frontier - Moved to locker
    ears: ClothingHeadsetEngineering
  #storage:
    #back:
    #- Stuff
