- type: job
  id: SalvageSpecialist
  name: job-name-salvagespec
  description: job-description-salvagespec
  playTimeTracker: JobSalvageSpecialist
  setPreference: false # Frontier
  requirements:
<<<<<<< HEAD
    - !type:OverallPlaytimeRequirement
      time: 10800
=======
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 10800 # 3 hrs
#    - !type:OverallPlaytimeRequirement
#      time: 36000 #10 hrs
>>>>>>> r1remote/master
  icon: "JobIconShaftMiner"
  startingGear: SalvageSpecialistGear
  supervisors: job-supervisors-hire # Frontier
  accessGroups: # Frontier
  - GeneralAccess # Frontier

- type: startingGear
  id: SalvageSpecialistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSalvageSpecialist
    id: SalvagePDA
    ears: ClothingHeadsetCargo
  #storage:
    #back:
    #- Stuff
