- type: job
  id: Passenger
  name: job-name-passenger
  description: job-description-passenger
  playTimeTracker: JobPassengerOld
  setPreference: false # Frontier
  startingGear: PassengerGear
  icon: "JobIconPassenger"
<<<<<<< HEAD
#  supervisors: job-supervisors-everyone
  accessGroups: # Frontier
  - GeneralAccess # Frontier
=======
  supervisors: job-supervisors-everyone
#  access: # Corvax-MRP
#  - Maintenance
>>>>>>> r1remote/master

- type: startingGear
  id: PassengerGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey
  #storage:
    #back:
    #- Stuff
