- type: job
  id: ServiceWorker
  name: job-name-serviceworker
  description: job-description-serviceworker
  playTimeTracker: JobServiceWorker
  setPreference: false # Frontier
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800
  startingGear: ServiceWorkerGear
  icon: "JobIconServiceWorker"
  supervisors: job-supervisors-service
<<<<<<< HEAD
  accessGroups: # Frontier
  - GeneralAccess # Frontier
  # access: # Frontier
  # - Service # Frontier
  # - Maintenance # Frontier
  # - Bar # Frontier
  # - Kitchen # Frontier
  # extendedAccess: # Frontier
  # - Hydroponics # Frontier
=======
  canBeAntag: true # Corvax-MRP: Available not only for newbies
  access:
  - Service
  - Maintenance
  - Bar
  - Kitchen
  extendedAccess:
  - Hydroponics
>>>>>>> r1remote/master

- type: startingGear
  id: ServiceWorkerGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: ServiceWorkerPDA
    ears: ClothingHeadsetService
  #storage:
    #back:
    #- Stuff
