- type: job
  id: Visitor
  name: job-name-visitor
  description: job-description-visitor
  playTimeTracker: JobVisitor
  canBeAntag: false
  icon: JobIconVisitor
  setPreference: false
<<<<<<< HEAD
#  overrideConsoleVisibility: true # Frontier
  accessGroups: # Frontier
  - GeneralAccess # Frontier
  # access: # Frontier
  # - Maintenance # Frontier
  # extendedAccess: # Frontier
  # - External # Frontier
=======
  overrideConsoleVisibility: true
#  access: # Corvax-MRP
#  - Maintenance
>>>>>>> r1remote/master
