- type: job
  id: ResearchDirector
  name: job-name-rd
  description: job-description-rd
  playTimeTracker: JobResearchDirector
  setPreference: false # Frontier
  requirements:
<<<<<<< HEAD
    - !type:OverallPlaytimeRequirement
      time: 144000 #40 hrs
=======
    - !type:DepartmentTimeRequirement
      department: Science
      time: 54000 #15 hrs # Corvax-RoleTime
#    - !type:OverallPlaytimeRequirement
#      time: 144000 #40 hrs
>>>>>>> r1remote/master
  weight: 10
  startingGear: ResearchDirectorGear
  icon: "JobIconResearchDirector"
  supervisors: job-supervisors-captain
  canBeAntag: false
  ## Frontier: commented stuff below out
  # access:
  # - Research
  # - Command
  # - Maintenance
  # - ResearchDirector
  # - Brig
  # - Cryogenics
  # special:
  # - !type:AddImplantSpecial
  #   implants: [ MindShieldImplant ]
  # - !type:AddComponentSpecial
  #   components:
  #     - type: CommandStaff
  ## End Frontier: commented stuff above out
  accessGroups: # Frontier
  - GeneralAccess # Frontier

- type: startingGear
  id: ResearchDirectorGear
  equipment:
    id: RnDPDA
    ears: ClothingHeadsetRD
  storage:
    back:
    - Flash
