- type: job
  id: ResearchAssistant
  name: job-name-research-assistant
  description: job-description-research-assistant
  playTimeTracker: JobResearchAssistant
  requirements:
<<<<<<< HEAD
#    - !type:DepartmentTimeRequirement
#      department: Science
#      time: 10800
#      inverted: true # stop playing intern if you're good at science!
    - !type:OverallPlaytimeRequirement # Frontier
      time: 10800 # Frontier
=======
    - !type:DepartmentTimeRequirement
      department: Science
      time: 36000 #10 hrs # Corvax-RoleTime
      inverted: true # stop playing intern if you're good at science!
>>>>>>> r1remote/master
  startingGear: ResearchAssistantGear
  icon: "JobIconResearchAssistant"
  supervisors: job-supervisors-science
  canBeAntag: false
  # access: # Frontier
  # - Research # Frontier
  # - Maintenance # Frontier
  setPreference: false # Frontier
  accessGroups: # Frontier
  - GeneralAccess # Frontier

- type: startingGear
  id: ResearchAssistantGear
  equipment:
    shoes: ClothingShoesColorWhite
    id: ResearchAssistantPDA
    ears: ClothingHeadsetScience
    pocket2: BookScientistsGuidebook
  #storage:
    #back:
    #- Stuff
