- type: antag
  id: HeadRev
  name: roles-antag-rev-head-name
  antagonist: true
  setPreference: false
  objective: roles-antag-rev-head-objective
<<<<<<< HEAD
  # guides: [ Revolutionaries ] # Frontier: removed, irrelevant
=======
  guides: [ Revolutionaries ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 108000 # 30h # Corvax-RoleTime
>>>>>>> r1remote/master

- type: antag
  id: Rev
  name: roles-antag-rev-name
  antagonist: true
  setPreference: false
  objective: roles-antag-rev-objective
  # guides: [ Revolutionaries ] # Frontier: removed, irrelevant

- type: startingGear
  id: HeadRevGear
  storage:
    back:
    - Flash
    - ClothingEyesGlassesSunglasses
