name: "Labels: PR"

on:
- pull_request_target

jobs:
  labeler:
    if: github.actor != 'IanComradeBot'
    runs-on: [self-hosted, linux, x64]
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/labeler@v5
